<a href="https://colab.research.google.com/github/RiazullJannat/Python_For_Ai_Ml/blob/main/mid_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**registred email: ramimk097@gmail.com**

In [1]:
import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

#Q1. Use  NumPy arrays ,  the emp_ages and emp_income.
#Ans:

In [9]:

print('emp_ages array:')
print(emp_ages)
print(f'Data type: {emp_ages.dtype}')
print(f'Number of dimensions: {emp_ages.ndim}')
print(f'Shape: {emp_ages.shape}')
print(f'Total number of elements: {emp_ages.size}')
print("------X------")
print('emp_income array:')
print(emp_income)
print(f'Data type: {emp_income.dtype}')
print(f'Number of dimensions: {emp_income.ndim}')
print(f'Shape: {emp_income.shape}')
print(f'Total number of elements: {emp_income.size}')

emp_ages array:
[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Data type: int64
Number of dimensions: 1
Shape: (50,)
Total number of elements: 50
------X------
emp_income array:
[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]
Data type: int64
Number of dimensions: 1
Shape: (50,)
Total number of elements: 50

Q2.
Using NumPy functions:

Ans:

In [12]:
print(f"maximum salary: {np.max(emp_income)}")
print(f"minimum salary: {np.min(emp_income)}")
print(f"average salary: {np.mean(emp_income)}")
print(f"average age: {np.mean(emp_ages)}")

maximum salary: 94722
minimum salary: 35452
average salary: 68409.48
average age: 35.44

Q3.
From the emp_ages array:
ans:

In [19]:
filtered_employees = data[(data['emp_age']>25) & (data['emp_age']<40) & (data['emp_salary']>50000)]
print("Employees aged between 25 and 40 with salary greater than 50,000:")
display(filtered_employees)

print(f"employees count: {len(filtered_employees)}")

Employees aged between 25 and 40 with salary greater than 50,000:

    emp_id  emp_age  emp_salary                role
4      105       37       72187   Backend Developer
5      106       37       58915          HR Manager
7      108       35       92864     Sales Executive
9      110       38       90494        HR Executive
10     111       31       68641   Backend Developer
12     113       29       56879     Sales Executive
13     114       38       83682  Operations Manager
14     115       27       94722    Digital Marketer
19     120       32       74146   Backend Developer
23     124       26       78354  Software Developer
25     126       37       79898  Operations Manager
26     127       26       59682    Digital Marketer
29     130       30       73700          Accountant
37     138       30       84188          Accountant
38     139       27       52013          HR Manager
48     149       31       59727    Digital Marketer

employees count: 16

Q4.
Create a new NumPy array where each employee’s age is adjusted based on:

ans:

In [20]:
avj = np.mean(emp_ages)
new_arr = np.where(emp_ages < avj, emp_ages + 4, emp_ages + 2)

print("Original emp_ages array:")
print(emp_ages)

print("\nUpdated emp_ages array (new_arr):")
print(new_arr)

print(f"\nAverage age used for condition: {avj:.2f}")

Original emp_ages array:
[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]

Updated emp_ages array (new_arr):
[56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]

Average age used for condition: 35.44

Q5.
Using NumPy:

Ans:

In [34]:
tech_roles = ['Software Developer', 'Backend Developer','Digital Marketer']

old_total_salary_expense = np.sum(data['emp_salary'])
print(f"Old Total Salary Expense: {old_total_salary_expense:,.2f}")

modified_data = data.copy()

modified_data['emp_salary'] = np.where(modified_data['role'].isin(tech_roles), modified_data['emp_salary'] *0.08, modified_data['emp_salary'])

new_total_salary_expense = np.sum(modified_data['emp_salary'])
print(f"New Total Salary Expense: {new_total_salary_expense:,.2}")

print(f"overall increase {new_total_salary_expense - old_total_salary_expense:,.2f}")

Old Total Salary Expense: 3,420,474.00
New Total Salary Expense: 2.2e+06
overall increase -1,199,841.92

Q6.
Load the staff_data.csv file into a Pandas DataFrame.

ans:

In [41]:
df_file = pd.read_csv('staff_data.csv')
df_file.head(3)
df_file.info()
df_file.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

Q7.
Filter the dataset to include only:

ans:

In [45]:
filtered_employees = df_file.loc[(df_file['emp_age']>25) & (df_file['emp_age']<40)].sort_values(by='emp_id')
filtered_employees.head(3)

   emp_id  emp_age  emp_salary               role
4     105       37       72187  Backend Developer
5     106       37       58915         HR Manager
7     108       35       92864    Sales Executive

Q8.
Filter the DataFrame to show only employees working in the "HR" role.

ans:

In [57]:
hr_employess = df_file.loc[df_file['role']=='HR Manager']
print(hr_employess)
print(f"\nhr employess len is: {len(hr_employess['emp_id'])}")

    emp_id  emp_age  emp_salary        role
0      101       54       51725  HR Manager
5      106       37       58915  HR Manager
38     139       27       52013  HR Manager
45     146       52       41061  HR Manager

hr employess len is: 4

Q9.
Sort the DataFrame by:

ans:

In [61]:
sotrtedData = df_file.sort_values(by='emp_age').sort_values(by='emp_salary',ascending=False)
sotrtedData[['emp_id', 'role', 'emp_salary']].head(5)

    emp_id               role  emp_salary
14     115   Digital Marketer       94722
36     137    Sales Executive       94427
7      108    Sales Executive       92864
15     116  Financial Analyst       91041
44     145       HR Executive       90794

Q10.
Using .loc:

ans:

In [66]:
roles = ['Backend Developer', 'Software Developer']

data = df_file.copy()

data["previous_salary"] = data['emp_salary']

data.loc[data['role'].isin(roles), "new_salary"] = data['emp_salary'] * 1.12

data.loc[~data['role'].isin(roles), "new_salary"] = data['emp_salary'] * 1.05

data["increase_of_salary"]=data["new_salary"]-data["previous_salary"]

data[["role","previous_salary","new_salary","increase_of_salary"]]

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager            51725    54311.25             2586.25
1            Accountant            38495    40419.75             1924.75
2    Operations Manager            35452    37224.60             1772.60
3      Digital Marketer            82295    86409.75             4114.75
4     Backend Developer            72187    80849.44             8662.44
5            HR Manager            58915    61860.75             2945.75
6     Backend Developer            76159    85298.08             9139.08
7       Sales Executive            92864    97507.20             4643.20
8       Sales Executive            76155    79962.75             3807.75
9          HR Executive            90494    95018.70             4524.70
10    Backend Developer            68641    76877.92             8236.92
11  Marketing Executive            48079    50482.95             2403.95
12      Sales Executive            56879    59722.95             2843.95
13   Operations Manager            83682    87866.10             4184.10
14     Digital Marketer            94722    99458.10             4736.10
15    Financial Analyst            91041    95593.05             4552.05
16      Sales Executive            48899    51343.95             2444.95
17   Operations Manager            68744    72181.20             3437.20
18   Software Developer            63187    70769.44             7582.44
19    Backend Developer            74146    83043.52             8897.52
20      Sales Executive            75641    79423.05             3782.05
21      Sales Executive            47678    50061.90             2383.90
22           Accountant            76760    80598.00             3838.00
23   Software Developer            78354    87756.48             9402.48
24         HR Executive            60584    63613.20             3029.20
25   Operations Manager            79898    83892.90             3994.90
26     Digital Marketer            59682    62666.10             2984.10
27         HR Executive            71888    75482.40             3594.40
28   Software Developer            51086    57216.32             6130.32
29           Accountant            73700    77385.00             3685.00
30      Sales Executive            82550    86677.50             4127.50
31  Marketing Executive            71447    75019.35             3572.35
32     Digital Marketer            76100    79905.00             3805.00
33    Backend Developer            72269    80941.28             8672.28
34   Software Developer            73314    82111.68             8797.68
35   Software Developer            87428    97919.36            10491.36
36      Sales Executive            94427    99148.35             4721.35
37           Accountant            84188    88397.40             4209.40
38           HR Manager            52013    54613.65             2600.65
39      Sales Executive            63326    66492.30             3166.30
40  Marketing Executive            44396    46615.80             2219.80
41     Digital Marketer            59500    62475.00             2975.00
42         HR Executive            55523    58299.15             2776.15
43           Accountant            58602    61532.10             2930.10
44         HR Executive            90794    95333.70             4539.70
45           HR Manager            41061    43114.05             2053.05
46   Software Developer            82331    92210.72             9879.72
47   Software Developer            73048    81813.76             8765.76
48     Digital Marketer            59727    62713.35             2986.35
49  Marketing Executive            50398    52917.90             2519.90